Finished init.d script

diff --git a/src/debian/ardukey-auth-server.init b/src/debian/ardukey-auth-server.init
--- a/src/debian/ardukey-auth-server.init
+++ b/src/debian/ardukey-auth-server.init
@@ -1,97 +1,150 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          ardukey-auth
-# Required-Start:    $all
-# Required-Stop:     $all
+# Provides:          ardukey-auth-server
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: ArduKey authentication server.
 # Description:       ArduKey authentication server.
 ### END INIT INFO
 
-## Author: Bastian Raschke <bastian.raschke@posteo.de>
-##
+# Author: Bastian Raschke <bastian.raschke@posteo.de>
+#
 
-## Do NOT "set -e"
+# Do NOT "set -e"
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="ArduKey authentication server"
-NAME="ardukey-auth"
+NAME="ardukey-auth-server"
 DAEMON="/usr/sbin/${NAME}"
 DAEMON_ARGS=""
 PIDFILE="/var/run/${NAME}.pid"
 SCRIPTNAME="/etc/init.d/${NAME}"
+RUNASUSER="www-data"
+PROCESS_EXECUTABLE="/usr/bin/python3"
 
-## Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+# Exit if the package is not installed
+[ -x "${DAEMON}" ] || exit 0
 
-## Define LSB log_* functions
+# Read configuration variable file if it is present
+[ -r "/etc/default/${NAME}" ] && . "/etc/default/${NAME}"
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions
 . /lib/lsb/init-functions
 
 
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
 
+    # Note: Cause of the daemon is interpreted by Python,
+    # we have to assign the interpreter executable (in this case python3)!
+    start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
+        --exec "${PROCESS_EXECUTABLE}" \
+        --chuid "${RUNASUSER}" \
+        --test > /dev/null \
+    || return 1
 
+    # --make-pidfile: Create PID file (the daemon does not)
+    # --background: Fork own daemon process
+    start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
+        --exec "${DAEMON}" \
+        --chuid "${RUNASUSER}" \
+        --make-pidfile --background \
+        -- "${DAEMON_ARGS}" \
+    || return 2
+}
 
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
 
+    # Note: Cause of the daemon is interpreted by Python,
+    # we have to assign the interpreter executable (in this case python3)!
+    start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" \
+        --exec "${PROCESS_EXECUTABLE}" \
+        --retry=TERM/30/KILL/5
+    RETVAL="${?}"
 
+    # Return here, if daemon could not be stopped
+    [ "${RETVAL}" = 2 ] && return 2
 
+    # Delete PID file
+    rm -f "${PIDFILE}"
 
+    # Sleep a bit for sure
+    sleep 1
+
+    # Return other return codes
+    return "${RETVAL}"
+}
 
 
 case "${1}" in
 
     start)
-        ## Be sure the service is not already running
-        if ( test -f "${PIDFILE}" ); then
-           log_failure_msg "${NAME} is already running"
-           exit 1
-        fi
-
-        log_daemon_msg "Starting ${DESC}" "${NAME}"
-        start-stop-daemon --start --make-pidfile --pidfile "${PIDFILE}" --chuid www-data:www-data --background --exec "${DAEMON}" -- "${DAEMON_ARGS}"
-
-        if ( test "${?}" = 0 ); then
-           log_end_msg 0
-           exit 0
-        else
-           rm -f "${PIDFILE}"
-           log_end_msg 1
-           exit 1
-        fi
+        [ "${VERBOSE}" != no ] && log_daemon_msg "Starting ${DESC}" "${NAME}"
+        do_start
+        case "${?}" in
+            0|1) [ "${VERBOSE}" != no ] && log_end_msg 0 ;;
+            2) [ "${VERBOSE}" != no ] && log_end_msg 1 ;;
+        esac
     ;;
 
     stop)
-        ## Be sure the service is running
-        if ( ! test -f "${PIDFILE}" ); then
-           log_failure_msg "${NAME} is not running"
-           exit 1
-        fi
-
-        log_daemon_msg "Stopping ${DESC}" "${NAME}"
-        start-stop-daemon --stop --quiet --oknodo --pidfile "${PIDFILE}" 2> /dev/null
-
-        if ( test "${?}" = 0 ); then
-           rm -f "${PIDFILE}"
-           log_end_msg 0
-           exit 0
-        else
-           log_end_msg 1
-           exit 1
-        fi
-    ;;
-
-    restart|force-reload)
-        ${0} stop && sleep 2 && ${0} start
+        [ "${VERBOSE}" != no ] && log_daemon_msg "Stopping ${DESC}" "${NAME}"
+        do_stop
+        case "${?}" in
+            0|1) [ "${VERBOSE}" != no ] && log_end_msg 0 ;;
+            2) [ "${VERBOSE}" != no ] && log_end_msg 1 ;;
+        esac
     ;;
 
     status)
-        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" 2> /dev/null
-        exit 0
+        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" \
+        && exit 0 || exit "${?}"
+    ;;
+
+    restart|force-reload)
+        log_daemon_msg "Restarting ${DESC}" "${NAME}"
+        do_stop
+        case "${?}" in
+            0|1)
+                do_start
+                case "${?}" in
+                    0) log_end_msg 0 ;;
+                    1) log_end_msg 1 ;; # Old process is still running
+                    *) log_end_msg 1 ;; # Failed to start
+                esac
+            ;;
+            *)
+                # Failed to stop
+                log_end_msg 1
+            ;;
+        esac
     ;;
 
     *)
-        echo "Usage: ${SCRIPTNAME} {start|stop|restart|status}" >&2
+        echo "Usage: ${SCRIPTNAME} {start|stop|status|restart|force-reload}" >&2
         exit 3
     ;;
 
 esac
+
+# Exit with exit status of last executed command
+:
